Conditions:
  EnvStaging : {"Fn::Equals" : [ "${self:custom.stage}", "staging"]}
  EnvProd : {"Fn::Equals" : [ "${self:custom.stage}", "prod"]}
  CreateResource: {"Fn::Or": [{"Condition": "EnvStaging"}, {"Condition": "EnvProd" }]}