stage: ${opt:stage, self:provider.stage}
enabled:
  dev: true
  staging: true
  prod: true
  
environment:
  dev: staging
  staging: staging
  prod: production

domains:
  dev: api.dev.upacaipalmas.com
  staging: api.staging.upacaipalmas.com
  prod: api.upacaipalmas.com

customDomain:
  basePath: hello
  domainName: ${self:custom.domains.${self:custom.stage}}
  stage: "${self:custom.stage}"
  createRoute53Record: true

webpack:
  keepOutputDirectory: true
  includeModules: true
  webpackConfig: ./webpack.config.js
  forceExclude:
    - aws-sdk
  packager: "yarn"
  packagerOptions:
    scripts:
      - rm -rf node_modules/aws-sdk

alerts:
  stages:
    - prod
    - staging
  topics:
    ok:
      topic: "arn:aws:sns:us-east-1:AWS_ID:${self:service}-${self:custom.stage}-alerts-alarm"
    alarm: 
      topic: "arn:aws:sns:us-east-1:AWS_ID:${self:service}-${self:custom.stage}-alerts-alarm"

  definitions:
    functionErrors:
      description: Lambda Error - ERROR
      treatMissingData: notBreaching
      period: 300
      threshold: 5
    functionThrottles:
      description: Lambda Throttle - ERROR
      treatMissingData: notBreaching
      period: 300
      threshold: 5
    functionDuration:
      description: Lambda Timeout - WARNING
      threshold: 30000 #milliseconds
      treatMissingData: notBreaching 
  global:
    - functionErrors
    - functionThrottles
    - functionDuration